### PR TITLE
add functionality needed for TAS essential features

### PR DESCRIPTION
**Pull request by MikeJerred**
I've added the features needed here so that we don't need to modify GWCA to make TAS toolbox

### CODE REVIEW

**Comment by henderkes** [comment]
I don't get the point. Minipets are not targettable in the game, so this makes no sense.

If you want to modify toolbox behaviour, use a plugin.

**Comment by MikeJerred** [comment]
Point is to reduce the absolute mess that currently exists, with half the community using random dlls posted on discord. This change will allow a modified Toolbox to have the required features that TAS runners need, without enabling those features for normal users.

Currently, we need to modify GWCA as well as Toolbox which is more difficult to maintain in a fork.

**Comment by henderkes** [comment]
This wouldn't change a thing. Instead of uncommenting the GW::Agents::IsAgentTargettable call, you'd pass an extra parameter in your fork. Same amount of work, completely unnecessary change.

> Point is to reduce the absolute mess that currently exists,

That's what the plugin system is for. You can patch this with a plugin in 4 lines of code and don't have to do anything on toolbox updates.

```cpp
using GetIsAgentTargettableFn = decltype(&GW::Agents::GetIsAgentTargettable);
GetIsAgentTargettableFn GetIsAgentTargettable_Func = nullptr;

void TargetEverything::Initialize(ImGuiContext* ctx, const ImGuiAllocFns fns, const HMODULE toolbox_dll)
{
    ToolboxPlugin::Initialize(ctx, fns, toolbox_dll);

    GW::Scanner::Initialize(toolbox_dll);
    GetIsAgentTargettable_Func = reinterpret_cast<GetIsAgentTargettableFn>(GW::Scanner::Find("\x55\x8B\xEC\x8B\x45\x08\x85\xC0\x74\x0\xF6\x80\x9C\x00\x00\x00\x0\x74", "xxxxxxxxx?xxxxxx?x"));
    // hook function, do what you wish there
}
```

**Comment by henderkes** [comment]
And for the dialog stuff, just hook the SendDialog Func in your plugin and then override the default toolbox /dialog chat command.

**Comment by MikeJerred** [comment]
Looking at the plugin thing now.
I'm not sure how to do what I need though, if I were to hook the SendDialog function like this:

```cpp
address = Scanner::Find("\x89\x4b\x24\x8b\x4b\x28\x83\xe9\x00", "xxxxxxxxx");
SendDialog_Func = (SendDialog_pt)Scanner::FunctionFromNearCall(address + 0x15);
HookBase::CreateHook(SendDialog_Func, OnSendDialog, (void**)&RetSendDialog);
```

Then presumably my hook will execute, and then toolbox's hook will run right after. The toolbox hook will then prevent sending the dialog. What can I do in my hook to send the dialog through?

**Comment by MikeJerred** [comment]
Also realized the code in this PR is not correct, it should be this:

```cpp
bool SendDialogRaw(uint32_t dialog_id) {
            if (!RetSendDialog)
                return false;
            RetSendDialog(dialog_id);
            return true;
        }
```

**Comment by MikeJerred** [comment]
Right now it is just way easier to build a custom dll and share it so :/

**Comment by henderkes** [comment]
> Then presumably my hook will execute, and then toolbox's hook will run right after. The toolbox hook will then prevent sending the dialog. What can I do in my hook to send the dialog through?

Toolbox only hooks and prevents sending from UI messages, if you SendDialog directly, it won't intercept it.
Last but not least, you can also bring back CtoS and... do pretty much everything.

**Comment by MikeJerred** [comment]
> > Then presumably my hook will execute, and then toolbox's hook will run right after. The toolbox hook will then prevent sending the dialog. What can I do in my hook to send the dialog through?
> 
> Toolbox only hooks and prevents sending from UI messages, if you SendDialog directly, it won't intercept it. Last but not least, you can also bring back CtoS and... do pretty much everything.

That was not the case when I was testing, the dialog got blocked. Looking at the code:



Long story short it is would be easiest to enable these features under a checkbox in the official Toolbox, which is disabled by default, and has a big warning saying "YOU CAN GET EXTRA BANNED MORE SO THAN THE DISCLAIMER ON THE TOOLBOX FAQ. ENABLE AT OWN RISK"

I don't see how there is any harm in having this in toolbox.
Meanwhile there are a bunch of people running dubious dlls under admin rights, in an application which is manually disabled for antivirus. Also the userbase of Toolbox is segregated with people not wanting to update.

**Comment by henderkes** [comment]
> Long story short it is would be easiest to enable these features under a checkbox in the official Toolbox, which is disabled by default, and has a big warning saying "YOU CAN GET EXTRA BANNED MORE SO THAN THE DISCLAIMER ON THE TOOLBOX FAQ. ENABLE AT OWN RISK"

This is not happening. If it's in toolbox, it means it's supported. If someone does this with plugins, they're not coming from us and it doesn't fall back on us.

> That was not the case when I was testing, the dialog got blocked. Looking at the code:

You're right, the GWCA SendDialog hook converts all SendDialog calls to UI Messages. I'm not sure why we do this to be honest.
You can patch Toolbox DialogModule blocking these however:
```cpp
const auto address = GW::Scanner;;Find("C6 00 ? 5D C3 5D"); // in toolbox dll
GW::MemoryPatcher::SetPatch(address + 2, "\x00", 1);
```

This simply patches the status->blocked = true to status->blocked = false in OnPreUIMessage..

**Pull request closed without merging**
