### PR TITLE
Implement GetTransform, QueryAltitude.

### PR DESCRIPTION
**Pull request by 544449**
image

### CODE REVIEW

**Comment by 3vcloud** [comment]
Meant to ask @544449 do you have a good candidate for the examples folder that uses this in practice?

**Comment by 544449** [comment]
I tried modifying examples; can't get any examples to build in VS 2019, there are errors. 
MinHook builds fine, I can make GWCA build with minor modifications, but for examples I lost my patience. 
Is there a simple way to make examples build?
[vs19.txt](https://github.com/GregLando113/GWCA/files/8497192/vs19.txt)

**Comment by 544449** [comment]
maybe @franneck94 changes will fix my issues.

**Comment by franneck94** [comment]
I've got the armory example compiling with vs2022

**Pull request merged**
